### ISSUE TITLE
Wrong download command

### ISSUE THREAD

**Issue by RoiuGit** [dementive/Victoria3Tools#1]
Hi, I think there's a mistake in the download command you provided (in the README.md): 'import os; path=sublime.packages_path(); (os.makedirs(path) if not os.path.exists(path) else None); window.run_command('exec', {'cmd': ['git', 'clone', 'https://github.com/dementive/VicTools', 'VicTools'], 'working_dir': path})'

It should be 'import os; path=sublime.packages_path(); (os.makedirs(path) if not os.path.exists(path) else None); window.run_command('exec', {'cmd': ['git', 'clone', 'https://github.com/dementive/**Victoria3Tools**', '**Victoria3Tools**'], 'working_dir': path})' to work.

**Comment by dementive** [comment]
Fixed it thanks for letting me know
